"""Central optimizable parameter bounds for genome DSL knobs."""

from __future__ import annotations

from q_backend.backtesting.strategy_registry import StrategyParamSpec

MA_TYPE_CHOICES = sorted(["sma", "ema", "wma", "smma", "hma"])
VOL_ESTIMATOR_CHOICES = ["yang_zhang", "close_to_close"]

GENOME_PARAM_BOUNDS: dict[str, StrategyParamSpec] = {
    "short_period": StrategyParamSpec(
        name="short_period",
        label="Short Period",
        type="int",
        default=50,
        min=2,
        max=400,
        step=1,
    ),
    "long_period": StrategyParamSpec(
        name="long_period",
        label="Long Period",
        type="int",
        default=200,
        min=2,
        max=400,
        step=1,
    ),
    "short_ma_type": StrategyParamSpec(
        name="short_ma_type",
        label="Short MA Type",
        type="categorical",
        default="sma",
        choices=MA_TYPE_CHOICES,
    ),
    "long_ma_type": StrategyParamSpec(
        name="long_ma_type",
        label="Long MA Type",
        type="categorical",
        default="sma",
        choices=MA_TYPE_CHOICES,
    ),
    "threshold": StrategyParamSpec(
        name="threshold",
        label="Threshold",
        type="float",
        default=0.0,
        min=0.0,
        max=100.0,
        step=0.01,
    ),
    "period": StrategyParamSpec(
        name="period",
        label="Period",
        type="int",
        default=20,
        min=2,
        max=400,
        step=1,
    ),
    "oversold": StrategyParamSpec(
        name="oversold",
        label="Oversold",
        type="float",
        default=30.0,
        min=0.0,
        max=50.0,
        step=0.5,
    ),
    "overbought": StrategyParamSpec(
        name="overbought",
        label="Overbought",
        type="float",
        default=70.0,
        min=50.0,
        max=100.0,
        step=0.5,
    ),
    "num_std": StrategyParamSpec(
        name="num_std",
        label="Std Dev Multiplier",
        type="float",
        default=2.0,
        min=0.5,
        max=5.0,
        step=0.1,
    ),
    "fast_period": StrategyParamSpec(
        name="fast_period",
        label="Fast Period",
        type="int",
        default=12,
        min=2,
        max=100,
        step=1,
    ),
    "slow_period": StrategyParamSpec(
        name="slow_period",
        label="Slow Period",
        type="int",
        default=26,
        min=2,
        max=400,
        step=1,
    ),
    "signal_period": StrategyParamSpec(
        name="signal_period",
        label="Signal Period",
        type="int",
        default=9,
        min=2,
        max=100,
        step=1,
    ),
    "band_pct": StrategyParamSpec(
        name="band_pct",
        label="Band (%)",
        type="float",
        default=0.0,
        min=0.0,
        max=5.0,
        step=0.01,
    ),
    "holding_period": StrategyParamSpec(
        name="holding_period",
        label="Holding Period (bars)",
        type="int",
        default=10,
        min=1,
        max=60,
        step=1,
    ),
    "ma_type": StrategyParamSpec(
        name="ma_type",
        label="MA Type",
        type="categorical",
        default="sma",
        choices=MA_TYPE_CHOICES,
    ),
    "lookback_bars": StrategyParamSpec(
        name="lookback_bars",
        label="Lookback (bars)",
        type="int",
        default=252,
        min=20,
        max=1000,
        step=1,
    ),
    "rebalance_bars": StrategyParamSpec(
        name="rebalance_bars",
        label="Rebalance (bars)",
        type="int",
        default=21,
        min=1,
        max=252,
        step=1,
    ),
    "vol_window": StrategyParamSpec(
        name="vol_window",
        label="Volatility window",
        type="int",
        default=63,
        min=2,
        max=400,
        step=1,
    ),
    "vol_estimator": StrategyParamSpec(
        name="vol_estimator",
        label="Volatility estimator",
        type="categorical",
        default="yang_zhang",
        choices=VOL_ESTIMATOR_CHOICES,
    ),
    "factor": StrategyParamSpec(
        name="factor",
        label="Scale Factor",
        type="float",
        default=1.0,
        min=0.01,
        max=100.0,
        step=0.01,
    ),
}
