from enum import Enum
from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


class OrderAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"


class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


def _utcnow():
    return datetime.now(timezone.utc)


class Order(BaseModel):
    """
    Represents an order generated by a strategy during backtesting.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique identifier for the order")
    symbol: str = Field(..., description="The traded instrument symbol")
    action: OrderAction = Field(..., description="BUY or SELL")
    order_type: OrderType = Field(..., description="MARKET, LIMIT, or STOP")
    quantity: float = Field(..., description="Amount/volume to trade")
    price: Optional[float] = Field(
        None, description="Limit or Stop price, depending on order_type"
    )
    status: OrderStatus = Field(
        default=OrderStatus.PENDING, description="Current status of the order"
    )
    created_at: datetime = Field(
        default_factory=_utcnow, description="When the order was generated"
    )


class Trade(BaseModel):
    """
    Represents an executed trade (or position) in the backtesting engine.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str = Field(..., description="Unique identifier for the trade")
    order_id: str = Field(..., description="ID of the order that initiated this trade")
    symbol: str = Field(..., description="The traded instrument symbol")
    action: OrderAction = Field(..., description="BUY or SELL")
    quantity: float = Field(..., description="Amount/volume traded")
    entry_time: datetime = Field(..., description="Datetime the trade was opened")
    entry_price: float = Field(..., description="Execution price at entry")
    exit_time: Optional[datetime] = Field(
        None, description="Datetime the trade was closed"
    )
    exit_price: Optional[float] = Field(None, description="Execution price at exit")
    status: TradeStatus = Field(default=TradeStatus.OPEN, description="OPEN or CLOSED")
    pnl: Optional[float] = Field(None, description="Profit and loss for the trade")
    commission: float = Field(0.0, description="Transaction costs")
    point_value: float = Field(
        1.0, description="Multiplier representing value per point/contract size"
    )


class SignalAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"


class Signal(BaseModel):
    """
    Represents a trading signal generated by a TradingStrategy.
    A Position Sizer or Broker interface will turn these into Orders.
    """

    model_config = ConfigDict(from_attributes=True)

    symbol: str = Field(..., description="The traded instrument symbol")
    action: SignalAction = Field(..., description="BUY, SELL, HOLD, or CLOSE")
    strength: float = Field(
        1.0,
        description="Signal strength, typically between 0.0 and 1.0",
        ge=0.0,
        le=1.0,
    )
    created_at: datetime = Field(
        default_factory=_utcnow, description="When the signal was generated"
    )
